---
- hosts: paloalto
  tasks: 
    - name: Configure NTP servers and timezone on PaloAlto devices
      paloaltonetworks.panos.panos_mgtconfig:
        provider: "{{ credentials }}"
        ntp_server_primary: "{{ ntp_server_primary }}"
        ntp_server_secondary: "{{ ntp_server_secondary }}"
        timezone: "Europe/Warsaw"

    - name: Commit changes on PaloAlto devices
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ credentials }}"