---
- hosts: cisco
  tasks:
    - name: Create running-config backups
      cisco.ios.ios_config:
        backup: true
        backup_options:
          dir_path: "/~/network-labs/lab1-enterprise-ha-network/config/"
          filename: "{{ inventory_hostname }}.txt"
