---
- hosts: cisco
  gather_facts: false
  tasks:
    - name: Delete vIOS banners on Cisco devices
      cisco.ios.ios_config:
        lines:
          - no banner exec
          - no banner incoming
        save_when: modified
