---
- hosts: cisco
  become: yes

  tasks:
    - name: Configure NTP on Cisco devices
      cisco.ios.ios_ntp_global:
        config: 
          servers: "{{ ntp_servers }}"
          source: "{{ ntp_source_interface }}" 
          update_calendar: true
        state: replaced
    
    - name: Configure timezone on Cisco devices
      cisco.ios.ios_config:
        lines:
          - clock timezone CET 1 0
          - clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00

    - name: Save running to startup when changed
      cisco.ios.ios_config:
        save_when: modified