---
- hosts: cisco
  become: yes
  gather_facts: no

  tasks:
    - name: Configure SNMPv3 "ZABBIX" group and user on Cisco devices
      cisco.ios.ios_snmp_server:
        config:
          groups:
            - group: "ZABBIX"
              version: "v3"
              version_option: "priv"
          users:
            - username: "{{ snmp_user }}"
              group: "ZABBIX"
              version: "v3"            
              authentication:
                algorithm: "sha"
                password: "{{ snmp_auth_pass }}"
              encryption:
                priv: "aes"
                password: "{{ snmp_priv_pass }}"
                priv_option: 128
        state: replaced

    - name: Save running to startup when changed
      cisco.ios.ios_config:
        save_when: modified
