# Logging messages from ACCESS switches
if $fromhost-ip startswith '10.1.99.4' then /var/log/network/asw1.log
& stop
if $fromhost-ip startswith '10.1.99.5' then /var/log/network/asw2.log
& stop
if $fromhost-ip startswith '10.1.99.6' then /var/log/network/asw3.log
& stop
# Logging messages from DISTRIBUTION switches
if $fromhost-ip startswith '10.1.99.2' then /var/log/network/dsw1.log
& stop
if $fromhost-ip startswith '10.1.99.3' then /var/log/network/dsw2.log
& stop
# Logging messages from PA firewalls
if $fromhost-ip startswith '10.0.0.224' then /var/log/network/fw1.log
& stop
if $fromhost-ip startswith '10.0.0.225' then /var/log/network/fw2.log
& stop
# Logging messages from edge routers
if $fromhost-ip startswith '10.0.0.226' then /var/log/network/r1.log
& stop
if $fromhost-ip startswith '10.0.0.227' then /var/log/network/r2.log
& stop