---
all:
  children:

    cisco:
      children:
        switches:
          children:
            access_switches:
              hosts:
                ASW-1:
                  ansible_host: 10.1.99.4
                ASW-2:
                  ansible_host: 10.1.99.5
                ASW-3:
                  ansible_host: 10.1.99.6    
            distribution_switches:
              hosts:
                DSW-1:
                  ansible_host: 10.1.99.2
                DSW-2:
                  ansible_host: 10.1.99.3
        routers:
          hosts:
            R1:
              ansible_host: 10.0.0.226
            R2:
              ansible_host: 10.0.0.227

    paloalto:
      children:
        firewalls:
          hosts:
            FW-1:
              ansible_host: 10.0.0.224
            FW-2:
              ansible_host: 10.0.0.225

